[application]

[web.app]

# HTML title tag content
title = "birdhouse-rs"

# include `assets` in web platform
[web.resource]
static_dir = "static"

# Additional CSS style files
style = []

# Additional JavaScript files
script = []

[web.resource.dev]

# Javascript code file
# serve: [dev-server] only
script = []
