services:
  birdhouse:
    build: .
    container_name: birdhouse-rs
    network_mode: host
    env_file:
      - .env
    volumes:
      - ./public/gallery_cache:/usr/local/app/public/gallery_cache
    restart: unless-stopped