services:
  birdhouse:
    build: .
    container_name: birdhouse-rs
    network_mode: host
    env_file:
      - .env
    volumes:
      - ./public/gallery_cache:/app/public/gallery_cache
    restart: unless-stopped

volumes:
  gallery_cache:
    driver: local