services:
  birdhouse:
    build: .
    container_name: birdhouse-rs
    network_mode: host
    env_file:
      - .env
    volumes:
      - ./gallery:/usr/local/app/gallery
      - ./data:/usr/local/app/data
    restart: unless-stopped